### ISSUE TITLE
Finish CSS Checklist

### ISSUE THREAD

**Issue by ChiaHan1** [ChiaHan1/fa22-cse110-lab3#21]
### Task:
CSS Checklist

### Features:
General **CSS Topics**

### Details:
- [x] **Comment:** Write down comments to make your css easier to read
- [x] **Color:** Apply colors to your HTML elements
   - Red, green, blue, alpha values e.g. `rgb(r, g, b)` or `rgba(r, g, b, a)`
   - Hex codes e.g. `#FFF` or `#FFFFFF`
   - Hue, saturation, lightness, alpha values e.g. `hsl(h, s, l)` or `hsla(h, s, l, a)`
   - Color name e.g. `orange`
- [x] **Background:** Apply background styles to your elements
   - `background-color`
- [x] **Unit:** Units of measurement for sizing and spacing your elements
   - Use 3 unique relative units total
   - Use 3 unique absolute units total
- [x] **Box Model:** Configure the containers that holds your HTML content
   - Margin: Spacing between html elements
      - Long (`margin-top`, `margin-bottom`, `margin-left`, `margin-right`)
      - Short (`margin: <top> <right> <bottom> <left>`)
      - Auto Margins (`margin: auto`)
    
   - Padding: Spacing within html elements
      - Long (`padding-top`, `padding-bottom`, `padding-left`, `padding-right`)
      - Short (`padding: <top> <right> <bottom> <left>`)
- [x]  **Borders:** Borders around html elements
   > Hints: apply borders before testing out padding and margin to better understand the difference between the two
   - `border-style`
   - `border-color`
   - `border-width`
   - `border-radius`
- [x] **Text:** Style your text
   - `color`
   - `text-decoration`
   - `text-align`
- [x] **Display:**
   - Experiment with these values: `none`, `block`, `inline-block`, `inline`. Include at least two of them in your page.
   - Apply theses values to the `display` property
- [x] **Sizing:** Set the height and width for an element
   - `height`
   - `width`
   - `max-width`
   - `min-width`
- [x] **Position:** Element positioning on the page
   - 2 of the following values: `static`, `relative`, `fixed`, `absolute`, `sticky`
      - Apply these values to the `position` property
- [x] **Pseudo-class:** Elements that exist in your document conditionally
   - `:hover`
   - `:active`
- [x] **Layouts:**
   - Flexbox: Allow your elements to lay themselves out automatically
      - Apply `flex` to the `display` property
      - Must have more than two children within the element that is using flexbox. Must use minimum three of the flexbox related attributes
   - Grid: Instantiate a grid for your layouts
      - Apply `grid` to the `display` property
      - Must have more than two children within the element that is using the grid. Must use a minimum of three of the grid related attributes
- [x] **Responsiveness:** Make your website friendly for multiple devices
   - At least one query based on the screen width
   - Media Query
- [x] **Fonts:** Pick varying font styles to make your text fun to read
   - Include and use a 3rd party font ([Google Fonts](https://fonts.google.com/))
