### ISSUE TITLE
Use CSS Selectors

### ISSUE THREAD

**Issue by ChiaHan1** [ChiaHan1/fa22-cse110-lab3#22]
### Task:
Use CSS Selectors

### Features:
CSS Selectors

### Details:
CSS selectors allow you to select the HTML element you want to style. Each type of selector targets a different identifier on your HTML element.

- [x] Class Selector (`.class`)
- [x] ID Selector (`#id`)
- [x] Universal Selector (`*`)
- [x] Element Selector (`element`) 
- [x] Attribute Selector (e.g. `[attribute=foo]`)     
- [x] Pseudo-class Selector (e.g. `p:hover`)
- [x] Selector List (`element, element`)
- [x] Combinators (you must use one of each)
   - [x] Descendant Combinator (`element element`)
   - [x] Child Combinator (`element > element`)
   - [x] General sibling combinator (`element ~ element`)
   - [x] Adjacent sibling combinator (`element + element`)
   - [x] Combining Two Selectors (`element.class`)
